environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
	- choco install redis-64
  - redis-server --service-install
  - redis-server --service-start
  - npm install

before_build:
build: off
after_build:

before_test:
  - node --version
  - npm --version

test_script:
  - npm test

after_test:

