name: CI

on: [pull_request, push]

env:
  CI: true

jobs:
  lint:
    uses: haraka/.github/.github/workflows/lint.yml@master

  test:
    needs: [lint]
    uses: haraka/.github/.github/workflows/ubuntu.yml@master
